# Generated by Django 5.0.7 on 2024-08-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techrealm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='autor',
            field=models.CharField(max_length=100),
        ),
    ]
